### ISSUE TITLE
Cryptic fail status

### ISSUE THREAD

**Issue by DBS-Max** [Zilong-Li/BaseVarC#3] opened 2020-01-10 21:44 UTC
I am running BaseVarC in a docker container using nextflow, I am feeding it a BAM file from BWA MEM and calling each chromosome independently (using 1-n not 0-n).

However, BaseVarC ends with error code 1 but the only output is: 

```
basetype start -- Fri Jan 10 21:05:43 2020
begin to read bams and save as tmp file
./GRC194242428.bam
```

I'd like to give you more info, but that's what I got.

**Comment by Zilong-Li** [comment] 2020-01-11 02:12
Hey,

1. the input must be a bamlist file, in which one bam per row. you should check the usage and the given example script in `test` directory.

2. the given region must be `chr:start-end` format. I added checking region in todo list but forgot it. It will be added later.

3. BaseVarC is intended for large-scale low coverage sequencing data. It is for population calling not single individual calling.

**Comment by DBS-Max** [comment] 2020-01-13 16:21
Thanks, I will look at it further, I have been using a bamlist and the proper region format, e.g.

```
  BaseVarC basetype \
    -i bams.txt \
    -r GRCh38_full_analysis_set_plus_decoy_hla.fa \
    -s chr1:1-248956422 \
    -o chr1 \
    -t 10 \
    -b 100
```

How large does the scale need to be? Have been testing with a single sample so far.

**Comment by DiDeoxy** [comment] 2020-01-22 17:25
Hey, I am still having this issue.

bam.list:
```
B82070_sorted_md.bam
B82065_sorted_md.bam
B82072_sorted_md.bam
GRC194242436_sorted_md.bam
GRC194242437_sorted_md.bam
GRC194242428_sorted_md.bam
GRC194242432_sorted_md.bam
GRC194242433_sorted_md.bam
B82069_sorted_md.bam
B82071_sorted_md.bam
GRC194242431_sorted_md.bam
GRC194242435_sorted_md.bam
GRC194242430_sorted_md.bam
GRC194242429_sorted_md.bam
B82067_sorted_md.bam
B82066_sorted_md.bam
B82068_sorted_md.bam
B82064_sorted_md.bam
ERR262997_sorted_md.bam
GRC194242434_sorted_md.bam
```

command:
```
  find . -maxdepth 1 -name "*bam" | sed 's|^\./||' > bams.list
  BaseVarC basetype \
    -i bams.list \
    -r GRCh38_full_analysis_set_plus_decoy_hla.fa \
    -s chr1:1-248956422 \
    -o chr1 \
    -t 18 \
    -b 100
```

output:
```
basetype start -- Wed Jan 22 17:20:42 2020
begin to read bams and save as tmp file
B82070_sorted_md.bam
Process `base_var_c (chr1:1-248956422)` terminated with an error exit status (1)
```

All of these bam files work with other variant callers (gatk4, deepvariant, octopus, strelka2). And this region works with them as well.

**Comment by Zilong-Li** [comment] 2020-01-23 05:37
I should have written a more detailed document. 

See **Note on performance** section: This `--batch` controls how many samples will be bundled as a batch. So it should be smaller than the number of given bams, that is, in your script `-b 100` is out of bounds. 

Also, be careful of the RAM when you set large number of threads and region scale to whole chromosome. It will get killed if out of RAM of your server.

Thanks.

**Comment by DBS-Max** [comment] 2020-01-23 17:11
Hi, Thank you for your response.

Unfortunately this didn't fix the error. I dropped -b to 10, threads to 5, and gave it 60GB of memory but i still get the same error.

Maybe its a temp file creation permission error? I built a docker container base that I use to make new containers for the tools I'm using including BaseVarC. None of these other tools have such a problem though.

**Comment by Zilong-Li** [comment] 2020-01-28 06:57
Hey,

I didn't test docker scenario yet. Did you run the `test/test.sh` script successfully with or without docker?

**Comment by DBS-Max** [comment] 2020-02-14 22:34
Hey, sorry for the delayed response, I am just getting back to this now.

I ran test/test.sh and it ran with no issues. 

I have also set up several different intervals that I want to call variants in, BaseVarC runs successfully for the majority of these but fails on some. These intervals all work for other callers.

This is a command with a region that fails:

```
  BaseVarC basetype \
    -i bams.list \
    -r GRCh38_full_analysis_set_plus_decoy_hla.fa \
    -s chr12:106492961-107492962 \
    -o chr12 \
    -t 2 \
    -b 10
```

This is the contents of bams.list:

```
B82071_sorted_md.bam
B82069_sorted_md.bam
B82065_sorted_md.bam
ERR262997_sorted_md.bam
B82068_sorted_md.bam
B82064_sorted_md.bam
B82066_sorted_md.bam
B82070_sorted_md.bam
B82072_sorted_md.bam
B82067_sorted_md.bam
```

**Comment by Zilong-Li** [comment] 2020-02-15 04:55
Any logs output or error code?

If the program fails without any errors output, I think maybe there is no SNP called within the region due to small population. You can use `--keep_tmp` option to keep tmp files and check whether they are empty or not. I will add more output info and checkers when I am free of current work.   

Best

**Comment by DBS-Max** [comment] 2020-02-18 16:48
Hey, 

So I added more samples (up to 89 1x alignments using bwa mem). For some regions, BaseVarC succeeds, but for others, it fails. Failed regions output something like:

```
basetype start -- Tue Feb 18 16:27:50 2020
  ERR3239979_sorted_md.bam
```

If I remove the sample shown (sometimes multiple) BaseVarC succeeds on the region. Is this intended behaviour? I assume these samples have too few or no reads aligned in the region?

**Comment by DBS-Max** [comment] 2020-02-18 17:11
I expanded the regions (1MB to 5MB) but this didn't solve the problem. And the tmp folders are empty.

**Comment by DBS-Max** [comment] 2020-02-25 16:00
I expanded to full chromosomes, same issue.

**Comment by Zilong-Li** [comment] 2020-03-18 09:49
Sorry for my late reply. Now I can work on this.

This is an unexpected out_of_range exception I ever encounted due to the reads. But I remember it was fixed on my bams. However, it seems it won't work with your bam.

I just push new commits to the dev branch. Can you pull the latest dev commit and run again? I may need your help to reproduce the exception so that I can finally fix it. 

Thanks.

**Comment by DiDeoxy** [comment] 2020-03-19 19:25
Hey, Zilong-Li,

I got laid off from work this week so I no longer have access to the data to help you.

Apologies.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tengjun0520** [comment] 2020-07-03 02:15
Hi,Zilong-Li

 I have a issue. I always get an error when running

ERROR: something wrong when quering the reads in bam/161302.sorted.markdup.bam basic_string::substr: __pos (which is 161) > this->size() (which is 150)

Thanks

**Closed as completed** 2020-09-02 04:52 UTC
